// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AgriWand

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void PageSwap(lv_event_t * e);
void StartRecording(lv_event_t * e);    // BARU — kirim "1"
void CollectDataPoint(lv_event_t * e);  // BARU — kirim "2"
void SaveDataset(lv_event_t * e);       // Diubah — kirim "3"
void History_LoadDateDropdown();
void ViewDataset(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
