// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AgriWand

#include "ui.h"
#include "ExtButton.h"
#include "RTC_PCF85063.h"
#include <HardwareSerial.h>

void PageSwap(lv_event_t * e) { 
  uint16_t active_tab = lv_tabview_get_tab_act(ui_TabViewOverview);

  if(active_tab == 0) {
      // Tab pertama (TabOverview1) aktif
      lv_obj_set_style_bg_color(ui_PageIndicator1, lv_color_hex(0xFF6D00), LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_border_color(ui_PageIndicator1, lv_color_hex(0xFF6D00), LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_PageIndicator2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_border_color(ui_PageIndicator2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

  } else if(active_tab == 1) {
      // Tab kedua (TabOverview2) aktif
      lv_obj_set_style_bg_color(ui_PageIndicator1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_border_color(ui_PageIndicator1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_PageIndicator2, lv_color_hex(0xFF6D00), LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_border_color(ui_PageIndicator2, lv_color_hex(0xFF6D00), LV_PART_MAIN | LV_STATE_DEFAULT);
  }
}

void StartRecording(lv_event_t * e) {
    SensorSerial.println("1"); // Raspi: start recording
    Serial.println("[TX] 1 → Start Recording");
}

void CollectDataPoint(lv_event_t * e) {
    SensorSerial.println("2"); // Raspi: collect point
    Serial.println("[TX] 2 → Collect Point");
    // Balasan DATA: ditangani di ExtButton_Loop()
}

void SaveDataset(lv_event_t * e) {
    SensorSerial.println("3"); // Raspi: stop & save
    Serial.println("[TX] 3 → Save Dataset");
    // Balasan MSG:FILE_SAVED ditangani di ExtButton_Loop()
}

void History_LoadDateDropdown() {
    // Request history list dari Raspi
    SensorSerial.println("LIST_HISTORY");
    Serial.println("[TX] LIST_HISTORY → Requesting file list");
    // Respons HIST: ditangani di ExtButton_Loop()
}

void ViewDataset(lv_event_t * e) {
    // Tidak digunakan lagi (view only, tanpa detail)
}