// This file was generated by SquareLine Studio
// Modified for History list feature
// Project name: AgriWand

#ifndef UI_HISTORY_H
#define UI_HISTORY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_History
extern void ui_History_screen_init(void);
extern void ui_History_screen_destroy(void);
extern void ui_event_History(lv_event_t * e);
extern lv_obj_t * ui_History;
extern lv_obj_t * ui_SwipeUpArcB;
extern lv_obj_t * ui_HistoryTitle;
extern lv_obj_t * ui_HistoryList;
extern lv_obj_t * ui_HistoryStatus;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
