// This file was generated by SquareLine Studio
// Modified for History list feature
// Project name: AgriWand

#include "ui.h"

lv_obj_t * ui_History = NULL;
lv_obj_t * ui_SwipeUpArcB = NULL;
lv_obj_t * ui_HistoryTitle = NULL;
lv_obj_t * ui_HistoryList = NULL;
lv_obj_t * ui_HistoryStatus = NULL;

// event funtions
void ui_event_History(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_ScreenHistory(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        History_LoadDateDropdown();
    }
}

// build funtions

void ui_History_screen_init(void)
{
    ui_History = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_History, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_History, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_History, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Swipe up arc (navigation indicator)
    ui_SwipeUpArcB = lv_arc_create(ui_History);
    lv_obj_set_width(ui_SwipeUpArcB, 400);
    lv_obj_set_height(ui_SwipeUpArcB, 400);
    lv_obj_set_align(ui_SwipeUpArcB, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SwipeUpArcB, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_arc_set_range(ui_SwipeUpArcB, 0, 1);
    lv_arc_set_value(ui_SwipeUpArcB, 1);
    lv_arc_set_bg_angles(ui_SwipeUpArcB, 75, 105);
    lv_obj_set_style_arc_width(ui_SwipeUpArcB, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_SwipeUpArcB, lv_color_hex(0xFF6D00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SwipeUpArcB, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SwipeUpArcB, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_SwipeUpArcB, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Title
    ui_HistoryTitle = lv_label_create(ui_History);
    lv_obj_set_width(ui_HistoryTitle, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_HistoryTitle, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_HistoryTitle, 0);
    lv_obj_set_y(ui_HistoryTitle, -160);
    lv_obj_set_align(ui_HistoryTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HistoryTitle, "Field History");
    lv_obj_set_style_text_color(ui_HistoryTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HistoryTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HistoryTitle, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Scrollable list container
    ui_HistoryList = lv_obj_create(ui_History);
    lv_obj_remove_style_all(ui_HistoryList);
    lv_obj_set_width(ui_HistoryList, 320);
    lv_obj_set_height(ui_HistoryList, 280);
    lv_obj_set_x(ui_HistoryList, 0);
    lv_obj_set_y(ui_HistoryList, 10);
    lv_obj_set_align(ui_HistoryList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HistoryList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HistoryList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(ui_HistoryList, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HistoryList, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_scrollbar_mode(ui_HistoryList, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_set_scroll_dir(ui_HistoryList, LV_DIR_VER);

    // Status label (shown when loading or empty)
    ui_HistoryStatus = lv_label_create(ui_HistoryList);
    lv_obj_set_width(ui_HistoryStatus, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_HistoryStatus, LV_SIZE_CONTENT);
    lv_label_set_text(ui_HistoryStatus, "Loading...");
    lv_obj_set_style_text_color(ui_HistoryStatus, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HistoryStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HistoryStatus, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_History, ui_event_History, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_History, ui_event_ScreenHistory, LV_EVENT_ALL, NULL);
}

void ui_History_screen_destroy(void)
{
    if(ui_History) lv_obj_del(ui_History);

    ui_History = NULL;
    ui_SwipeUpArcB = NULL;
    ui_HistoryTitle = NULL;
    ui_HistoryList = NULL;
    ui_HistoryStatus = NULL;
}
