// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AgriWand

#include "ui.h"

lv_obj_t * ui_History = NULL;
lv_obj_t * ui_SwipeUpArcB = NULL;
lv_obj_t * ui_ChooseHistoryDrop = NULL;
lv_obj_t * ui_ContainerDataset = NULL;
lv_obj_t * ui_DatasetLabel = NULL;
// event funtions
void ui_event_History(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_ScreenHistory(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        History_LoadDateDropdown();
    }
}

void ui_event_ChooseHistoryDrop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ViewDataset(e);
    }
}

// build funtions

void ui_History_screen_init(void)
{
    ui_History = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_History, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_History, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_History, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwipeUpArcB = lv_arc_create(ui_History);
    lv_obj_set_width(ui_SwipeUpArcB, 400);
    lv_obj_set_height(ui_SwipeUpArcB, 400);
    lv_obj_set_align(ui_SwipeUpArcB, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SwipeUpArcB, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_range(ui_SwipeUpArcB, 0, 1);
    lv_arc_set_value(ui_SwipeUpArcB, 1);
    lv_arc_set_bg_angles(ui_SwipeUpArcB, 75, 105);
    lv_obj_set_style_arc_width(ui_SwipeUpArcB, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SwipeUpArcB, lv_color_hex(0xFF6D00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SwipeUpArcB, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SwipeUpArcB, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_SwipeUpArcB, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ChooseHistoryDrop = lv_dropdown_create(ui_History);
    lv_dropdown_set_options(ui_ChooseHistoryDrop, "31-1-2026 23:59:59");
    lv_dropdown_set_text(ui_ChooseHistoryDrop, "Choose Field Data");
    lv_obj_set_width(ui_ChooseHistoryDrop, 190);
    lv_obj_set_height(ui_ChooseHistoryDrop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChooseHistoryDrop, 0);
    lv_obj_set_y(ui_ChooseHistoryDrop, -150);
    lv_obj_set_align(ui_ChooseHistoryDrop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChooseHistoryDrop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ChooseHistoryDrop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChooseHistoryDrop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChooseHistoryDrop, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ChooseHistoryDrop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChooseHistoryDrop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChooseHistoryDrop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerDataset = lv_obj_create(ui_History);
    lv_obj_remove_style_all(ui_ContainerDataset);
    lv_obj_set_width(ui_ContainerDataset, 340);
    lv_obj_set_height(ui_ContainerDataset, 200);
    lv_obj_set_align(ui_ContainerDataset, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerDataset, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerDataset, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerDataset, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ContainerDataset, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_ContainerDataset, LV_DIR_VER);
    lv_obj_set_style_outline_color(ui_ContainerDataset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerDataset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerDataset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerDataset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ContainerDataset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ContainerDataset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ContainerDataset, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DatasetLabel = lv_label_create(ui_ContainerDataset);
    lv_obj_set_width(ui_DatasetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DatasetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DatasetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DatasetLabel,
                      "[\n    {\n        \"timestamp\": \"2026-02-23 02:19:23\",\n        \"soil\": {\n            \"temp\": 22.6,\n            \"hum\": 41.2,\n            \"ph\": 6.6000000000000005,\n            \"ec\": 18,\n            \"n\": 0,\n            \"p\": 1,\n            \"k\": 2\n        },\n        \"location\": {\n            \"lat\": 0.0,\n            \"lng\": 0.0,\n            \"valid\": false\n        }\n    },\n    {\n        \"timestamp\": \"2026-02-23 02:19:26\",\n        \"soil\": {\n            \"temp\": 22.8,\n            \"hum\": 42.0,\n            \"ph\": 6.2,\n            \"ec\": 18,\n            \"n\": 0,\n            \"p\": 1,\n            \"k\": 2\n        },\n        \"location\": {\n            \"lat\": -7.314516,\n            \"lng\": 110.496611,\n            \"valid\": true\n        }\n    }\n]");
    lv_obj_add_flag(ui_DatasetLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_DatasetLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ChooseHistoryDrop, ui_event_ChooseHistoryDrop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_History, ui_event_History, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_History, ui_event_ScreenHistory, LV_EVENT_ALL, NULL);
}

void ui_History_screen_destroy(void)
{
    if(ui_History) lv_obj_del(ui_History);

    // NULL screen variables
    ui_History = NULL;
    ui_SwipeUpArcB = NULL;
    ui_ChooseHistoryDrop = NULL;
    ui_ContainerDataset = NULL;
    ui_DatasetLabel = NULL;

}
