// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AgriWand

#ifndef UI_HISTORY_H
#define UI_HISTORY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_History
extern void ui_History_screen_init(void);
extern void ui_History_screen_destroy(void);
extern void ui_event_History(lv_event_t * e);
extern lv_obj_t * ui_History;
extern lv_obj_t * ui_SwipeUpArcB;
extern void ui_event_ChooseHistoryDrop(lv_event_t * e);
extern lv_obj_t * ui_ChooseHistoryDrop;
extern lv_obj_t * ui_ContainerDataset;
extern lv_obj_t * ui_DatasetLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

