// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AgriWand

#ifndef UI_IDLESCREEN_H
#define UI_IDLESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_IdleScreen
extern void ui_IdleScreen_screen_init(void);
extern void ui_IdleScreen_screen_destroy(void);
extern void ui_event_IdleScreen(lv_event_t * e);
extern lv_obj_t * ui_IdleScreen;
extern lv_obj_t * ui_SwipeUpArcA;
extern lv_obj_t * ui_DigitalClock;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_DevelopedbyLabel;
extern lv_obj_t * ui_LogoR2C;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

