// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AgriWand

#include "ui.h"

lv_obj_t * ui_IdleScreen = NULL;
lv_obj_t * ui_SwipeUpArcA = NULL;
lv_obj_t * ui_DigitalClock = NULL;
lv_obj_t * ui_DateLabel = NULL;
lv_obj_t * ui_DevelopedbyLabel = NULL;
lv_obj_t * ui_LogoR2C = NULL;
// event funtions
void ui_event_IdleScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_MainMenu_screen_init);
    }
}

// build funtions

void ui_IdleScreen_screen_init(void)
{
    ui_IdleScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IdleScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IdleScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IdleScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwipeUpArcA = lv_arc_create(ui_IdleScreen);
    lv_obj_set_width(ui_SwipeUpArcA, 400);
    lv_obj_set_height(ui_SwipeUpArcA, 400);
    lv_obj_set_align(ui_SwipeUpArcA, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SwipeUpArcA, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_range(ui_SwipeUpArcA, 0, 1);
    lv_arc_set_value(ui_SwipeUpArcA, 1);
    lv_arc_set_bg_angles(ui_SwipeUpArcA, 75, 105);
    lv_obj_set_style_arc_width(ui_SwipeUpArcA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SwipeUpArcA, lv_color_hex(0xFF6D00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SwipeUpArcA, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SwipeUpArcA, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_SwipeUpArcA, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DigitalClock = lv_label_create(ui_IdleScreen);
    lv_obj_set_width(ui_DigitalClock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigitalClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigitalClock, 0);
    lv_obj_set_y(ui_DigitalClock, -90);
    lv_obj_set_align(ui_DigitalClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigitalClock, "23:59");
    lv_obj_set_style_text_color(ui_DigitalClock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DigitalClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DigitalClock, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel = lv_label_create(ui_IdleScreen);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel, 0);
    lv_obj_set_y(ui_DateLabel, -50);
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel, "Monday, 31 Jan 2026");
    lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevelopedbyLabel = lv_label_create(ui_IdleScreen);
    lv_obj_set_width(ui_DevelopedbyLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevelopedbyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevelopedbyLabel, 1);
    lv_obj_set_y(ui_DevelopedbyLabel, 55);
    lv_obj_set_align(ui_DevelopedbyLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevelopedbyLabel, "Developed by");
    lv_obj_set_style_text_color(ui_DevelopedbyLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevelopedbyLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevelopedbyLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevelopedbyLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoR2C = lv_img_create(ui_IdleScreen);
    lv_img_set_src(ui_LogoR2C, &ui_img_1603299571);
    lv_obj_set_width(ui_LogoR2C, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_LogoR2C, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_LogoR2C, 0);
    lv_obj_set_y(ui_LogoR2C, 100);
    lv_obj_set_align(ui_LogoR2C, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoR2C, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoR2C, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_IdleScreen, ui_event_IdleScreen, LV_EVENT_ALL, NULL);

}

void ui_IdleScreen_screen_destroy(void)
{
    if(ui_IdleScreen) lv_obj_del(ui_IdleScreen);

    // NULL screen variables
    ui_IdleScreen = NULL;
    ui_SwipeUpArcA = NULL;
    ui_DigitalClock = NULL;
    ui_DateLabel = NULL;
    ui_DevelopedbyLabel = NULL;
    ui_LogoR2C = NULL;

}
