// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AgriWand

#include "ui.h"

lv_obj_t * ui_MainMenu = NULL;
lv_obj_t * ui_SwipeDownArc = NULL;
lv_obj_t * ui_CollectFieldButton = NULL;
lv_obj_t * ui_CollectFieldLabel = NULL;
lv_obj_t * ui_ViewHistoryLabel = NULL;
lv_obj_t * ui_ViewHistoryLabel1 = NULL;
// event funtions
void ui_event_MainMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_IdleScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_IdleScreen_screen_init);
    }
}

void ui_event_CollectFieldButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartRecording(e);
        lv_tabview_set_act(ui_TabViewOverview, 0, LV_ANIM_OFF);
        lv_obj_set_style_bg_color(ui_PageIndicator1, lv_color_hex(0xFF6D00), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_PageIndicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_PageIndicator1, lv_color_hex(0xFF6D00), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_opa(ui_PageIndicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_PageIndicator2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_PageIndicator2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_PageIndicator2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_PageIndicator2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_opa(ui_PageIndicator2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        _ui_screen_change(&ui_Overview, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Overview_screen_init);
        _ui_flag_modify(ui_SavedPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SaveButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ViewHistoryLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_History, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_History_screen_init);
    }
}

// build funtions

void ui_MainMenu_screen_init(void)
{
    ui_MainMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwipeDownArc = lv_arc_create(ui_MainMenu);
    lv_obj_set_width(ui_SwipeDownArc, 400);
    lv_obj_set_height(ui_SwipeDownArc, 400);
    lv_obj_set_align(ui_SwipeDownArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SwipeDownArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_range(ui_SwipeDownArc, 0, 1);
    lv_arc_set_value(ui_SwipeDownArc, 1);
    lv_arc_set_bg_angles(ui_SwipeDownArc, 255, 285);
    lv_obj_set_style_arc_width(ui_SwipeDownArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SwipeDownArc, lv_color_hex(0xFF6D00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SwipeDownArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SwipeDownArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_SwipeDownArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_CollectFieldButton = lv_btn_create(ui_MainMenu);
    lv_obj_set_width(ui_CollectFieldButton, 300);
    lv_obj_set_height(ui_CollectFieldButton, 65);
    lv_obj_set_x(ui_CollectFieldButton, 0);
    lv_obj_set_y(ui_CollectFieldButton, -50);
    lv_obj_set_align(ui_CollectFieldButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CollectFieldButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CollectFieldButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CollectFieldButton, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CollectFieldButton, lv_color_hex(0xFF6D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CollectFieldButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CollectFieldButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CollectFieldButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CollectFieldButton, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CollectFieldLabel = lv_label_create(ui_CollectFieldButton);
    lv_obj_set_width(ui_CollectFieldLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CollectFieldLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CollectFieldLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CollectFieldLabel, "Collect Field Data");

    ui_ViewHistoryLabel = lv_btn_create(ui_MainMenu);
    lv_obj_set_width(ui_ViewHistoryLabel, 240);
    lv_obj_set_height(ui_ViewHistoryLabel, 65);
    lv_obj_set_x(ui_ViewHistoryLabel, 0);
    lv_obj_set_y(ui_ViewHistoryLabel, 50);
    lv_obj_set_align(ui_ViewHistoryLabel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ViewHistoryLabel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ViewHistoryLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ViewHistoryLabel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ViewHistoryLabel, lv_color_hex(0xFF6D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ViewHistoryLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ViewHistoryLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ViewHistoryLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ViewHistoryLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ViewHistoryLabel1 = lv_label_create(ui_ViewHistoryLabel);
    lv_obj_set_width(ui_ViewHistoryLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ViewHistoryLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ViewHistoryLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ViewHistoryLabel1, "View History");

    lv_obj_add_event_cb(ui_CollectFieldButton, ui_event_CollectFieldButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ViewHistoryLabel, ui_event_ViewHistoryLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu, ui_event_MainMenu, LV_EVENT_ALL, NULL);

}

void ui_MainMenu_screen_destroy(void)
{
    if(ui_MainMenu) lv_obj_del(ui_MainMenu);

    // NULL screen variables
    ui_MainMenu = NULL;
    ui_SwipeDownArc = NULL;
    ui_CollectFieldButton = NULL;
    ui_CollectFieldLabel = NULL;
    ui_ViewHistoryLabel = NULL;
    ui_ViewHistoryLabel1 = NULL;

}
