// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AgriWand

#ifndef UI_MAINMENU_H
#define UI_MAINMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainMenu
extern void ui_MainMenu_screen_init(void);
extern void ui_MainMenu_screen_destroy(void);
extern void ui_event_MainMenu(lv_event_t * e);
extern lv_obj_t * ui_MainMenu;
extern lv_obj_t * ui_SwipeDownArc;
extern void ui_event_CollectFieldButton(lv_event_t * e);
extern lv_obj_t * ui_CollectFieldButton;
extern lv_obj_t * ui_CollectFieldLabel;
extern void ui_event_ViewHistoryLabel(lv_event_t * e);
extern lv_obj_t * ui_ViewHistoryLabel;
extern lv_obj_t * ui_ViewHistoryLabel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

