// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AgriWand

#ifndef UI_OVERVIEW_H
#define UI_OVERVIEW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Overview
extern void ui_Overview_screen_init(void);
extern void ui_Overview_screen_destroy(void);
extern lv_obj_t * ui_Overview;
extern void ui_event_TabViewOverview(lv_event_t * e);
extern lv_obj_t * ui_TabViewOverview;
extern lv_obj_t * ui_TabOverview1;
extern lv_obj_t * ui_NLabel;
extern lv_obj_t * ui_NBar;
extern lv_obj_t * ui_NContainer;
extern lv_obj_t * ui_NValue;
extern lv_obj_t * ui_PLabel;
extern lv_obj_t * ui_PBar;
extern lv_obj_t * ui_PContainer;
extern lv_obj_t * ui_PValue;
extern lv_obj_t * ui_KLabel;
extern lv_obj_t * ui_KBar;
extern lv_obj_t * ui_KContainer;
extern lv_obj_t * ui_KValue;
extern lv_obj_t * ui_TempPanel;
extern lv_obj_t * ui_TempValue;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_TempArc;
extern lv_obj_t * ui_TabOverview2;
extern lv_obj_t * ui_HumArc;
extern lv_obj_t * ui_HumContainer;
extern lv_obj_t * ui_HumValue;
extern lv_obj_t * ui_HumLabel;
extern lv_obj_t * ui_pHPanel;
extern lv_obj_t * ui_pHValue;
extern lv_obj_t * ui_pHLevelLabel;
extern lv_obj_t * ui_ECValue;
extern lv_obj_t * ui_ECLabel;
extern lv_obj_t * ui_OverviewPanel;
extern lv_obj_t * ui_PinpointLabel;
extern lv_obj_t * ui_PinpointValue;
extern lv_obj_t * ui_SeparateLine;
extern lv_obj_t * ui_PinpointTime;
extern void ui_event_SaveButton(lv_event_t * e);
extern lv_obj_t * ui_SaveButton;
extern lv_obj_t * ui_SaveLabel;
extern lv_obj_t * ui_PageIndicator1;
extern lv_obj_t * ui_PageIndicator2;
extern lv_obj_t * ui_SavedPanel;
extern lv_obj_t * ui_SavedSuccessLabel;
extern lv_obj_t * ui_GPSStatus;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

