// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AgriWand

#include "ui.h"

lv_obj_t* ui_Overview = NULL;
lv_obj_t* ui_TabViewOverview = NULL;
lv_obj_t* ui_TabOverview1 = NULL;
lv_obj_t* ui_NLabel = NULL;
lv_obj_t* ui_NBar = NULL;
lv_obj_t* ui_NContainer = NULL;
lv_obj_t* ui_NValue = NULL;
lv_obj_t* ui_PLabel = NULL;
lv_obj_t* ui_PBar = NULL;
lv_obj_t* ui_PContainer = NULL;
lv_obj_t* ui_PValue = NULL;
lv_obj_t* ui_KLabel = NULL;
lv_obj_t* ui_KBar = NULL;
lv_obj_t* ui_KContainer = NULL;
lv_obj_t* ui_KValue = NULL;
lv_obj_t* ui_TempPanel = NULL;
lv_obj_t* ui_TempValue = NULL;
lv_obj_t* ui_TempLabel = NULL;
lv_obj_t* ui_TempArc = NULL;
lv_obj_t* ui_TabOverview2 = NULL;
lv_obj_t* ui_HumArc = NULL;
lv_obj_t* ui_HumContainer = NULL;
lv_obj_t* ui_HumValue = NULL;
lv_obj_t* ui_HumLabel = NULL;
lv_obj_t* ui_pHPanel = NULL;
lv_obj_t* ui_pHValue = NULL;
lv_obj_t* ui_pHLevelLabel = NULL;
lv_obj_t* ui_ECValue = NULL;
lv_obj_t* ui_ECLabel = NULL;
lv_obj_t* ui_OverviewPanel = NULL;
lv_obj_t* ui_PinpointLabel = NULL;
lv_obj_t* ui_PinpointValue = NULL;
lv_obj_t* ui_SeparateLine = NULL;
lv_obj_t* ui_PinpointTime = NULL;
lv_obj_t* ui_SaveButton = NULL;
lv_obj_t* ui_SaveLabel = NULL;
lv_obj_t* ui_PageIndicator1 = NULL;
lv_obj_t* ui_PageIndicator2 = NULL;
lv_obj_t* ui_SavedPanel = NULL;
lv_obj_t* ui_SavedSuccessLabel = NULL;
// event funtions
void ui_event_TabViewOverview(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    PageSwap(e);
  }
}

void ui_event_SaveButton(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    SaveDataset(e);
    // Respons dari Raspi (FILE_SAVED / EMPTY_SESSION) ditangani oleh ExtButton_Loop
    // Beri waktu 4 detik agar respons tampil sebelum pindah layar
    _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 100, 4000, &ui_MainMenu_screen_init);
    _ui_flag_modify(ui_SaveButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD); // hidden
  }
}

// build funtions

void ui_Overview_screen_init(void) {
  ui_Overview = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Overview, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_Overview, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Overview, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_TabViewOverview = lv_tabview_create(ui_Overview, LV_DIR_TOP, 0);
  lv_obj_set_width(ui_TabViewOverview, 412);
  lv_obj_set_height(ui_TabViewOverview, 180);
  lv_obj_set_x(ui_TabViewOverview, 0);
  lv_obj_set_y(ui_TabViewOverview, 45);
  lv_obj_set_align(ui_TabViewOverview, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_TabViewOverview, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_TabViewOverview, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_TabViewOverview, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_TabOverview1 = lv_tabview_add_tab(ui_TabViewOverview, "Page1");
  lv_obj_set_scrollbar_mode(ui_TabOverview1, LV_SCROLLBAR_MODE_OFF);
  lv_obj_set_scroll_dir(ui_TabOverview1, LV_DIR_HOR);

  ui_NLabel = lv_label_create(ui_TabOverview1);
  lv_obj_set_width(ui_NLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_NLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_NLabel, -160);
  lv_obj_set_y(ui_NLabel, -60);
  lv_obj_set_align(ui_NLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_NLabel, "N");
  lv_obj_set_style_text_color(ui_NLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_NLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_NLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_NBar = lv_bar_create(ui_TabOverview1);
  lv_bar_set_range(ui_NBar, 0, 255);
  lv_bar_set_value(ui_NBar, 0, LV_ANIM_OFF);
  lv_bar_set_start_value(ui_NBar, 0, LV_ANIM_OFF);
  lv_obj_set_width(ui_NBar, 180);
  lv_obj_set_height(ui_NBar, 10);
  lv_obj_set_x(ui_NBar, -45);
  lv_obj_set_y(ui_NBar, -60);
  lv_obj_set_align(ui_NBar, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_NBar, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_NBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_NBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_bg_color(ui_NBar, lv_color_hex(0xDC2626), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_NBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  ui_NContainer = lv_obj_create(ui_TabOverview1);
  lv_obj_remove_style_all(ui_NContainer);
  lv_obj_set_width(ui_NContainer, 100);
  lv_obj_set_height(ui_NContainer, LV_SIZE_CONTENT);  /// 50
  lv_obj_set_x(ui_NContainer, -85);
  lv_obj_set_y(ui_NContainer, -45);
  lv_obj_set_align(ui_NContainer, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_NContainer, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_NContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
  lv_obj_clear_flag(ui_NContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_text_color(ui_NContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_NContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_NContainer, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_NValue = lv_label_create(ui_NContainer);
  lv_obj_set_width(ui_NValue, LV_SIZE_CONTENT);   /// 100
  lv_obj_set_height(ui_NValue, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_NValue, LV_ALIGN_CENTER);
  lv_label_set_text(ui_NValue, "--- mg/kg");

  ui_PLabel = lv_label_create(ui_TabOverview1);
  lv_obj_set_width(ui_PLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_PLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_PLabel, -160);
  lv_obj_set_y(ui_PLabel, -10);
  lv_obj_set_align(ui_PLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_PLabel, "P");
  lv_obj_set_style_text_color(ui_PLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_PLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_PLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_PBar = lv_bar_create(ui_TabOverview1);
  lv_bar_set_range(ui_PBar, 0, 255);
  lv_bar_set_value(ui_PBar, 0, LV_ANIM_OFF);
  lv_bar_set_start_value(ui_PBar, 0, LV_ANIM_OFF);
  lv_obj_set_width(ui_PBar, 180);
  lv_obj_set_height(ui_PBar, 10);
  lv_obj_set_x(ui_PBar, -45);
  lv_obj_set_y(ui_PBar, -10);
  lv_obj_set_align(ui_PBar, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_PBar, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_PBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_PBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_bg_color(ui_PBar, lv_color_hex(0xF59E0B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_PBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  ui_PContainer = lv_obj_create(ui_TabOverview1);
  lv_obj_remove_style_all(ui_PContainer);
  lv_obj_set_width(ui_PContainer, 100);
  lv_obj_set_height(ui_PContainer, LV_SIZE_CONTENT);  /// 50
  lv_obj_set_x(ui_PContainer, -85);
  lv_obj_set_y(ui_PContainer, 5);
  lv_obj_set_align(ui_PContainer, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_PContainer, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_PContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
  lv_obj_clear_flag(ui_PContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_text_color(ui_PContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_PContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_PContainer, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_PValue = lv_label_create(ui_PContainer);
  lv_obj_set_width(ui_PValue, LV_SIZE_CONTENT);   /// 100
  lv_obj_set_height(ui_PValue, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_PValue, LV_ALIGN_CENTER);
  lv_label_set_text(ui_PValue, "--- mg/kg");

  ui_KLabel = lv_label_create(ui_TabOverview1);
  lv_obj_set_width(ui_KLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_KLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_KLabel, -160);
  lv_obj_set_y(ui_KLabel, 40);
  lv_obj_set_align(ui_KLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_KLabel, "K");
  lv_obj_set_style_text_color(ui_KLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_KLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_KLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_KBar = lv_bar_create(ui_TabOverview1);
  lv_bar_set_range(ui_KBar, 0, 255);
  lv_bar_set_value(ui_KBar, 0, LV_ANIM_OFF);
  lv_bar_set_start_value(ui_KBar, 0, LV_ANIM_OFF);
  lv_obj_set_width(ui_KBar, 180);
  lv_obj_set_height(ui_KBar, 10);
  lv_obj_set_x(ui_KBar, -45);
  lv_obj_set_y(ui_KBar, 40);
  lv_obj_set_align(ui_KBar, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_KBar, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_KBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_KBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_bg_color(ui_KBar, lv_color_hex(0x10B981), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_KBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  ui_KContainer = lv_obj_create(ui_TabOverview1);
  lv_obj_remove_style_all(ui_KContainer);
  lv_obj_set_width(ui_KContainer, 100);
  lv_obj_set_height(ui_KContainer, LV_SIZE_CONTENT);  /// 50
  lv_obj_set_x(ui_KContainer, -85);
  lv_obj_set_y(ui_KContainer, 55);
  lv_obj_set_align(ui_KContainer, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_KContainer, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_KContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
  lv_obj_clear_flag(ui_KContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_text_color(ui_KContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_KContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_KContainer, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_KValue = lv_label_create(ui_KContainer);
  lv_obj_set_width(ui_KValue, LV_SIZE_CONTENT);   /// 100
  lv_obj_set_height(ui_KValue, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_KValue, LV_ALIGN_CENTER);
  lv_label_set_text(ui_KValue, "--- mg/kg");

  ui_TempPanel = lv_obj_create(ui_TabOverview1);
  lv_obj_set_width(ui_TempPanel, 75);
  lv_obj_set_height(ui_TempPanel, 75);
  lv_obj_set_x(ui_TempPanel, 125);
  lv_obj_set_y(ui_TempPanel, -20);
  lv_obj_set_align(ui_TempPanel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_TempPanel, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_TempPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_TempPanel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_TempValue = lv_label_create(ui_TempPanel);
  lv_obj_set_width(ui_TempValue, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_TempValue, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_TempValue, LV_ALIGN_CENTER);
  lv_label_set_text(ui_TempValue, "---");

  ui_TempLabel = lv_label_create(ui_TabOverview1);
  lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_TempLabel, 125);
  lv_obj_set_y(ui_TempLabel, 30);
  lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_TempLabel, "Temp");
  lv_obj_set_style_text_color(ui_TempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_TempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_TempLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_TempArc = lv_arc_create(ui_TabOverview1);
  lv_obj_set_width(ui_TempArc, 120);
  lv_obj_set_height(ui_TempArc, 120);
  lv_obj_set_x(ui_TempArc, 125);
  lv_obj_set_y(ui_TempArc, -20);
  lv_obj_set_align(ui_TempArc, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_TempArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_arc_set_range(ui_TempArc, 0, 45);
  lv_arc_set_value(ui_TempArc, 0);
  lv_arc_set_bg_angles(ui_TempArc, 300, 45);
  lv_arc_set_mode(ui_TempArc, LV_ARC_MODE_REVERSE);
  lv_obj_set_style_arc_width(ui_TempArc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_arc_color(ui_TempArc, lv_color_hex(0x10B981), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_opa(ui_TempArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_width(ui_TempArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  lv_obj_set_style_opa(ui_TempArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

  ui_TabOverview2 = lv_tabview_add_tab(ui_TabViewOverview, "Page2");
  lv_obj_set_scrollbar_mode(ui_TabOverview2, LV_SCROLLBAR_MODE_OFF);
  lv_obj_set_scroll_dir(ui_TabOverview2, LV_DIR_HOR);

  ui_HumArc = lv_arc_create(ui_TabOverview2);
  lv_obj_set_width(ui_HumArc, 70);
  lv_obj_set_height(ui_HumArc, 70);
  lv_obj_set_x(ui_HumArc, -145);
  lv_obj_set_y(ui_HumArc, -40);
  lv_obj_set_align(ui_HumArc, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_HumArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_arc_set_value(ui_HumArc, 0);
  lv_arc_set_bg_angles(ui_HumArc, 110, 310);
  lv_obj_set_style_arc_color(ui_HumArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_opa(ui_HumArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_width(ui_HumArc, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_arc_color(ui_HumArc, lv_color_hex(0x10B981), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_opa(ui_HumArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_width(ui_HumArc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  lv_obj_set_style_opa(ui_HumArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

  ui_HumContainer = lv_obj_create(ui_TabOverview2);
  lv_obj_remove_style_all(ui_HumContainer);
  lv_obj_set_width(ui_HumContainer, 100);
  lv_obj_set_height(ui_HumContainer, LV_SIZE_CONTENT);  /// 50
  lv_obj_set_x(ui_HumContainer, -100);
  lv_obj_set_y(ui_HumContainer, -40);
  lv_obj_set_align(ui_HumContainer, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_HumContainer, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_HumContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
  lv_obj_clear_flag(ui_HumContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_text_color(ui_HumContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_HumContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_HumContainer, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_HumValue = lv_label_create(ui_HumContainer);
  lv_obj_set_width(ui_HumValue, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_HumValue, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_HumValue, 20);
  lv_obj_set_y(ui_HumValue, -4);
  lv_obj_set_align(ui_HumValue, LV_ALIGN_CENTER);
  lv_label_set_text(ui_HumValue, "---%");

  ui_HumLabel = lv_label_create(ui_TabOverview2);
  lv_obj_set_width(ui_HumLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_HumLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_HumLabel, -110);
  lv_obj_set_y(ui_HumLabel, -10);
  lv_obj_set_align(ui_HumLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_HumLabel, "Humidity");
  lv_obj_set_style_text_color(ui_HumLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_HumLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_HumLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_pHPanel = lv_obj_create(ui_TabOverview2);
  lv_obj_set_width(ui_pHPanel, 60);
  lv_obj_set_height(ui_pHPanel, 60);
  lv_obj_set_align(ui_pHPanel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_pHPanel, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_pHPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_pHPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_pHPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_pHPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_pHPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_pHPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_pHPanel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_pHValue = lv_label_create(ui_pHPanel);
  lv_obj_set_width(ui_pHValue, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_pHValue, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_pHValue, LV_ALIGN_CENTER);
  lv_label_set_text(ui_pHValue, "---");

  ui_pHLevelLabel = lv_label_create(ui_TabOverview2);
  lv_obj_set_width(ui_pHLevelLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_pHLevelLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_pHLevelLabel, 0);
  lv_obj_set_y(ui_pHLevelLabel, 40);
  lv_obj_set_align(ui_pHLevelLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_pHLevelLabel, "pH Level");
  lv_obj_set_style_text_color(ui_pHLevelLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_pHLevelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_pHLevelLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ECValue = lv_label_create(ui_TabOverview2);
  lv_obj_set_width(ui_ECValue, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_ECValue, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_ECValue, 120);
  lv_obj_set_y(ui_ECValue, -40);
  lv_obj_set_align(ui_ECValue, LV_ALIGN_CENTER);
  lv_label_set_text(ui_ECValue, "--- uS/cm");
  lv_obj_set_style_text_color(ui_ECValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_ECValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_ECValue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_ECValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_ECValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_ECValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_ECValue, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ECLabel = lv_label_create(ui_TabOverview2);
  lv_obj_set_width(ui_ECLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_ECLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_ECLabel, 120);
  lv_obj_set_y(ui_ECLabel, -10);
  lv_obj_set_align(ui_ECLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_ECLabel, "Elec. Cond.");
  lv_obj_set_style_text_color(ui_ECLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_ECLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_ECLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_OverviewPanel = lv_obj_create(ui_Overview);
  lv_obj_set_width(ui_OverviewPanel, 450);
  lv_obj_set_height(ui_OverviewPanel, 400);
  lv_obj_set_x(ui_OverviewPanel, 0);
  lv_obj_set_y(ui_OverviewPanel, -250);
  lv_obj_set_align(ui_OverviewPanel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_OverviewPanel, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_OverviewPanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_OverviewPanel, lv_color_hex(0x196B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_OverviewPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_OverviewPanel, lv_color_hex(0x196B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_OverviewPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_PinpointLabel = lv_label_create(ui_OverviewPanel);
  lv_obj_set_width(ui_PinpointLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_PinpointLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_PinpointLabel, -25);
  lv_obj_set_y(ui_PinpointLabel, 100);
  lv_obj_set_align(ui_PinpointLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_PinpointLabel, "Pinpoint(s)\nCreated");
  lv_obj_set_style_text_color(ui_PinpointLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_PinpointLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_PinpointLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_PinpointLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_PinpointValue = lv_label_create(ui_OverviewPanel);
  lv_obj_set_width(ui_PinpointValue, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_PinpointValue, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_PinpointValue, 45);
  lv_obj_set_y(ui_PinpointValue, 100);
  lv_obj_set_align(ui_PinpointValue, LV_ALIGN_CENTER);
  lv_label_set_text(ui_PinpointValue, "0");
  lv_obj_set_style_text_color(ui_PinpointValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_PinpointValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_PinpointValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_SeparateLine = lv_obj_create(ui_OverviewPanel);
  lv_obj_set_width(ui_SeparateLine, 200);
  lv_obj_set_height(ui_SeparateLine, 2);
  lv_obj_set_x(ui_SeparateLine, 0);
  lv_obj_set_y(ui_SeparateLine, 120);
  lv_obj_set_align(ui_SeparateLine, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_SeparateLine, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_SeparateLine, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_SeparateLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_SeparateLine, lv_color_hex(0x2F7C4E), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_SeparateLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_PinpointTime = lv_label_create(ui_OverviewPanel);
  lv_obj_set_width(ui_PinpointTime, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_PinpointTime, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_PinpointTime, 0);
  lv_obj_set_y(ui_PinpointTime, 140);
  lv_obj_set_align(ui_PinpointTime, LV_ALIGN_CENTER);
  lv_label_set_text(ui_PinpointTime, "--:--:--");
  lv_obj_set_style_text_color(ui_PinpointTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_PinpointTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_PinpointTime, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_SaveButton = lv_btn_create(ui_OverviewPanel);
  lv_obj_set_width(ui_SaveButton, 130);
  lv_obj_set_height(ui_SaveButton, 40);
  lv_obj_set_x(ui_SaveButton, 0);
  lv_obj_set_y(ui_SaveButton, 175);
  lv_obj_set_align(ui_SaveButton, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_radius(ui_SaveButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_SaveButton, lv_color_hex(0x2F7C4E), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_SaveButton, lv_color_hex(0x2F7C4E), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_SaveButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_SaveButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_SaveLabel = lv_label_create(ui_SaveButton);
  lv_obj_set_width(ui_SaveLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_SaveLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_SaveLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_SaveLabel, "Save");
  lv_obj_set_style_text_color(ui_SaveLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_SaveLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_SaveLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_PageIndicator1 = lv_obj_create(ui_Overview);
  lv_obj_set_width(ui_PageIndicator1, 20);
  lv_obj_set_height(ui_PageIndicator1, 20);
  lv_obj_set_x(ui_PageIndicator1, -20);
  lv_obj_set_y(ui_PageIndicator1, 160);
  lv_obj_set_align(ui_PageIndicator1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_PageIndicator1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_PageIndicator1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_PageIndicator1, lv_color_hex(0xFF6D00), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_PageIndicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_PageIndicator1, lv_color_hex(0xFF6D00), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_PageIndicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_PageIndicator2 = lv_obj_create(ui_Overview);
  lv_obj_set_width(ui_PageIndicator2, 20);
  lv_obj_set_height(ui_PageIndicator2, 20);
  lv_obj_set_x(ui_PageIndicator2, 20);
  lv_obj_set_y(ui_PageIndicator2, 160);
  lv_obj_set_align(ui_PageIndicator2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_PageIndicator2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_PageIndicator2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_PageIndicator2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_PageIndicator2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_PageIndicator2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_PageIndicator2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_SavedPanel = lv_obj_create(ui_Overview);
  lv_obj_set_width(ui_SavedPanel, 400);
  lv_obj_set_height(ui_SavedPanel, 150);
  lv_obj_set_x(ui_SavedPanel, 0);
  lv_obj_set_y(ui_SavedPanel, 40);
  lv_obj_set_align(ui_SavedPanel, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_SavedPanel, LV_OBJ_FLAG_HIDDEN);                                /// Flags
  lv_obj_clear_flag(ui_SavedPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_SavedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_SavedPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_SavedPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_SavedPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_SavedPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_SavedPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_SavedPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_SavedPanel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_SavedPanel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_SavedSuccessLabel = lv_label_create(ui_SavedPanel);
  lv_obj_set_width(ui_SavedSuccessLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_SavedSuccessLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_SavedSuccessLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_SavedSuccessLabel, "Field data\nhas been saved!");

  lv_obj_add_event_cb(ui_TabViewOverview, ui_event_TabViewOverview, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_SaveButton, ui_event_SaveButton, LV_EVENT_ALL, NULL);
}

void ui_Overview_screen_destroy(void) {
  if (ui_Overview) lv_obj_del(ui_Overview);

  // NULL screen variables
  ui_Overview = NULL;
  ui_TabViewOverview = NULL;
  ui_TabOverview1 = NULL;
  ui_NLabel = NULL;
  ui_NBar = NULL;
  ui_NContainer = NULL;
  ui_NValue = NULL;
  ui_PLabel = NULL;
  ui_PBar = NULL;
  ui_PContainer = NULL;
  ui_PValue = NULL;
  ui_KLabel = NULL;
  ui_KBar = NULL;
  ui_KContainer = NULL;
  ui_KValue = NULL;
  ui_TempPanel = NULL;
  ui_TempValue = NULL;
  ui_TempLabel = NULL;
  ui_TempArc = NULL;
  ui_TabOverview2 = NULL;
  ui_HumArc = NULL;
  ui_HumContainer = NULL;
  ui_HumValue = NULL;
  ui_HumLabel = NULL;
  ui_pHPanel = NULL;
  ui_pHValue = NULL;
  ui_pHLevelLabel = NULL;
  ui_ECValue = NULL;
  ui_ECLabel = NULL;
  ui_OverviewPanel = NULL;
  ui_PinpointLabel = NULL;
  ui_PinpointValue = NULL;
  ui_SeparateLine = NULL;
  ui_PinpointTime = NULL;
  ui_SaveButton = NULL;
  ui_SaveLabel = NULL;
  ui_PageIndicator1 = NULL;
  ui_PageIndicator2 = NULL;
  ui_SavedPanel = NULL;
  ui_SavedSuccessLabel = NULL;
}
